version: "3.9"

services:
  backend:
    build: .
    container_name: movie-backend
    ports:
      - "3000:3000"
    depends_on:
      cassandra:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  cassandra:
    image: cassandra:4.1
    container_name: movie-cassandra
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=MovieCluster
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  cassandra_init:
    image: cassandra:4.1
    container_name: cassandra_init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init.cql:/init.cql:ro
    entrypoint: >
      sh -c "
        echo 'Waiting for Cassandra to be ready...';
        until cqlsh cassandra -e 'describe keyspaces'; do
          sleep 5;
        done;
        echo 'Running init.cql...';
        cqlsh cassandra -f /init.cql;
        echo 'Cassandra initialization done.';
      "
    restart: "no"
  redis:
    image: redis:7
    container_name: movie-redis
    restart: always
    
    

volumes:
  cassandra_data: